site_name: Just-API
theme:
  name: material
  palette:
    accent: blue
extra_javascript:
  - js/extra.js  
pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Basic Concepts: basic-concepts.md
  - CLI Reference: CLI.md
  - Features: features.md
  - Parallel exectuion: running-suites-in-parallel.md
  - Reporters: reporters.md
  - Examples: examples.md
markdown_extensions:
  - codehilite
  - admonition
google_analytics:
  - UA-120233669-1
  - auto
repo_name: Just-API
repo_url: https://github.com/kiranz/just-api
edit_uri: ""
extra:
    social:
      - type: 'github'
        link: 'https://github.com/kiranz/just-api'
      - type: 'twitter'
        link: 'https://twitter.com/just_api_'

