site_name: Just-API
theme:
  name: material
  palette:
    accent: blue
extra_javascript:
  - js/extra.js  
pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Docs:
      - basic-concepts.md
      - CLI.md
      - features.md
      - running-suites-in-parallel.md
      - reporters.md
      - examples.md
google_analytics:
  - UA-120233669-1
  - auto
repo_name: Just-API
repo_url: https://github.com/kiranz/just-api
edit_uri: ""
extra:
    social:
      - type: 'github'
        link: 'https://github.com/kiranz/just-api'
      - type: 'twitter'
        link: 'https://twitter.com/just_api_'

